const EVENTS = {
  GAME_START: 'GAME_START',
  GAME_OVER: 'GAME_OVER',
  GAME_RESTART: 'GAME_RESTART',

  GAME_INTRO_START: 'GAME_INTRO_START',
  GAME_INTRO_COMPLETE: 'GAME_INTRO_COMPLETE',

  PLAYER_ACTION: 'PLAYER_ACTION',

  ACHIEVEMENT: 'ACHIEVEMENT',
  HIGH_SCORE_UPDATE: 'HIGH_SCORE_UPDATE',

  // Betting mode events
  BETTING_MODE_ON: 'BETTING_MODE_ON',
  BETTING_MODE_OFF: 'BETTING_MODE_OFF',
  WAITING_FOR_JUMP: 'WAITING_FOR_JUMP',
  JUMP_SUCCESS: 'JUMP_SUCCESS',
  JUMP_FAIL: 'JUMP_FAIL',

  // Async score management
  HIGH_SCORE_FETCH: {
    REQUEST: 'HIGH_SCORE_FETCH_REQUEST',
    SUCCESS: 'HIGH_SCORE_FETCH_SUCCESS',
    FAIL: 'HIGH_SCORE_FETCH_FAIL',
  },
  HIGH_SCORE_SAVE: {
    REQUEST: 'HIGH_SCORE_SAVE_REQUEST',
    SUCCESS: 'HIGH_SCORE_SAVE_SUCCESS',
    FAIL: 'HIGH_SCORE_SAVE_FAIL',
  },
};

export default EVENTS;
